### PR TITLE
PHP8 Support for decimal 1.x

### PR DESCRIPTION
**Pull request by zlodes**
Related issue: 
https://github.com/php-decimal/ext-decimal/issues/43 

- [ ] Fixed tests
- [x] Fixed previous versions support (7.0 - 7.4)

### CODE REVIEW

**Comment by zlodes** [comment]
@rtheunissen Hi!
This PR has trouble with reflection test. It prints that null is allowed for some methods.

Can you help me?

**Comment by rtheunissen** [comment]
Hi @zlodes, I am taking a look at this now. It feels like yesterday that this issue was opened. Thank you for this work.

**Comment by rtheunissen** [comment]
This is excellent. What is the reason for the php8-specific tests?

**Comment by zlodes** [comment]
@rtheunissen some PHP8 and 7.4 errors have the different string representation. 

And I don't know how to fit it into one test.

**Comment by rtheunissen** [comment]
@zlodes I'm stuck on these reflection tests. I'm assuming "allow null" is the ? part of nullable type like ?int, but in this case the parameter does not have a type, it is `__construct($value, int $precision = DEFAULT_PRECISION)` so is that allow null or not? Perhaps 7.4/8 treat this case differently.

**Comment by rtheunissen** [comment]
I am going to inspect using `php --re decimal`

**Comment by rtheunissen** [comment]
Looking at the $value parameter:

PHP 7.4.9
`ZEND_ARG_INFO(0, name)`
allows_null: **false**
```
        Method [ <internal:decimal, ctor> public method __construct ] {

          - Parameters [2] {
            Parameter #0 [ <optional> $value ]
            Parameter #1 [ <optional> int $precision ]
          }
        }
```
PHP 8.0.9
`ZEND_ARG_INFO(0, name)`
allows_null: **true**
```
        Method [ <internal:decimal, ctor> public method __construct ] {

          - Parameters [2] {
            Parameter #0 [ <optional> $value = <default> ]
            Parameter #1 [ <optional> int $precision = <default> ]
          }
        }
```
```php
<?php

function testA($value) {}

$a = new ReflectionFunction('testA');

foreach ($a->getParameters() as $param) {
    var_dump($param->allowsNull());
}
```

^ This shows bool(true) for all versions, so I this should be the reference behavior.

Notice that we mark the parameters _optional_. In the `testA` method above the `$value` parameter is not optional. The only way to make it optional is to give it a type, or set its default to null, and because we have multiple types the only option is to set the default value to 0. I'll try some arginfo combinations in that direction.

**Comment by rtheunissen** [comment]
It seems that 7.4 does not have the argument info capabilities to make this consistent. I'll create the variation of the test for php8 and if issues about nullable types come up we can evaluate them as bugs then.

**Comment by rtheunissen** [comment]
I am going to merge this and make some minor changes thereafter. That makes 1.x compatible with PHP 8 which is worth a minor release along with anything else that was merged in the meantime.

**Comment by zlodes** [comment]
@rtheunissen thank you! 
Waiting for the release with PHP8.0 support. ❤️

**Comment by carlonicora** [comment]
Hello!

Sorry for pushing, but was curious to see if there is an ETA for the PHP8.0 support to be released.

Thanks A LOT for your work!

**Pull request merged**
